#!/bin/bash
#
#
#
yum clean all && yum makecache fast &> /dev/null
yum -y install nginx mariadb mariadb-server php php-cli php-curl php-fpm php-intl php-mcrypt php-mysql php-gd php-mbstring php-xml php-dom &> /dev/null
	echo "nginx,php,mariadb环境已经安装好."
systemctl restart nginx php-fpm mariadb
	echo "nginx,php,mariadb服务已开启."
cat >> /etc/nginx/conf.d/default.conf <<e
location ~ \.php$ {
            root           /usr/share/nginx/html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
e
#sed -ir '/^[\t ]#location ~ \.php$ {/localtion ~ \.php$ {' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#    root          html;/    root           /usr/share/nginx/html;' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#    fastcgi_pass   127.0.0.1:9000;/    fastcgi_pass   127.0.0.1:9000;' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#    fastcgi_index  index.php;/    fastcgi_index  index.php;' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;/    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#    include        fastcgi_params;/    include        fastcgi_params;' /etc/nginx/conf.d/default.conf
#sed -ir '/^[\t ]#}/}' /etc/nginx/conf.d/default.conf
systemctl restart nginx
	if [ $? -eq 0 ];then
		echo "nginx is ok."
	else
		echo "nginx faild!"
		exit
	fi
	echo "正在初始化Mysql密码..."
mysqladmin -u root password '123' &> /dev/null
	if [ $? -eq 0 ];then
		echo "Mysql 密码：123."
		echo "欢迎使用!"
		exit
	else
		echo "设置密码失败！"
		exit
	fi

