#!/usr/bin/env bash
#create time:
#file path:


yum -y groupinstall "Development Tools"
yum -y install ncurses ncurses-devel bison libgcrypt perl make cmake openssl-devel
groupadd mysql
useradd -M -g mysql -s /sbin/nologin mysql
mkdir -p /usr/local/mysql/{data,mysql,log,tmp}
tar xf mysql-boost-5.7.29.tar.gz -C /usr/local/
cd /usr/local/mysql-5.7.29 && cmake . \
-DCMAKE_INSTALL_PREFIX=/usr/local/mysql \
-DMYSQL_DATADIR=/usr/local/mysql/data \
-DDOWNLOAD_BOOST=1 \
-DWITH_BOOST=/usr/local/mysql-5.7.29/boost \
-DSYSCONFDIR=/etc \
-DWITH_INNOBASE_STORAGE_ENGINE=1 \
-DWITH_PARTITION_STORAGE_ENGINE=1 \
-DWITH_FEDERATED_STORAGE_ENGINE=1 \
-DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
-DWITH_MYISAM_STORAGE_ENGINE=1 \
-DENABLED_LOCAL_INFILE=1 \
-DENABLE_DTRACE=0 \
-DDEFAULT_CHARSET=utf8 \
-DDEFAULT_COLLATION=utf8_general_ci \
-DWITH_EMBEDDED_SERVER=1
make && make install
chown -R mysql.mysql /usr/local/mysql/*
echo "export PATH=$PATH:/usr/local/mysql/bin" >>/etc/profile.d/mysql.sh
. /etc/profile
mv /etc/{my.cnf,my.cnf.bak}
cp /usr/local/mysql/mysql-test/include/default_my.cnf /etc/my.cnf
cat >> /etc/my.cnf <<e
[mysqld]
basedir = /usr/local/mysql/mysql
datadir = /usr/local/mysql/data
tmpdir = /usr/local/mysql/tmp
socket = /usr/local/mysql/tmp/mysql.sock
pid_file = /usr/local/mysql/tmp/mysqld.pid
log_error = /usr/local/mysql/log/mysql_error.log
slow_query_log_file = /usr/local/mysql/log/slow_warn.log

server_id = 46
user = mysql
port = 3306
bind-address = 0.0.0.0
character-set-server = utf8
default_storage_engine = InnoDB
e
echo "手动source /etc/profile"
echo "修改/etc/my.cnf文件"
echo "修改好的配置文件   执行命令 cat /etc/my.cnf > /usr/local/mysql/mysql-test/include/default_my.cnf"
echo "初始化：mysqld --defaults-file=/etc/my.cnf --initialize --user='mysql'"
echo "启动：mysqld_safe --defaults-file=/etc/my.cnf &"
echo "修改秘密啊：mysqladmin -u root -p'' password ''"
echo "sock文件:ln -s /usr/local/mysql/tmp/mysql.sock /tmp/mysql.sock"
echo "设置开机自启1：cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld         chkconfig --add mysqld         chkconfig mysqld on"
echo "设置开机自启2：创建一个/usr/lib/systemd/system/*.service文件并配置 可以使用systemctl restart mysqld"
