#!/bin/bash
#
#
#
network_name=`ip a | grep '^2:' | awk -F": " '{print $2}'`
network_path="/etc/sysconfig/network-scripts/"
yum_path="/etc/yum.repos.d/"
ssh_path="/etc/ssh/sshd_config"
list()
{
	echo "+++++++++++++++++++++++++++++++++++++"
	echo "+    1.关闭防火墙                   +"
	echo "+    2.修改主机名                   +"
	echo "+    3.检查网络                     +"
	echo "+    4.统一网卡名称为eth            +"
	echo "+    5.配置yum仓库                  +"
	echo "+    6.修改ssh配置文件              +"
	echo "+    7.创建普通用户和密码并设置权限 +"
	echo "+    8.300s不操作自动注销root账户   +"
	echo "+    9.时间同步                     +"
	echo "+++++++++++++++++++++++++++++++++++++"
}
firewalld_stop()
{
	systemctl stop firewalld
	systemctl disable firewalld
	setenforce 0
	sed -i '/^SELINX=/c SELINUX=disabled' /etc/seliunx/config
}

hostname_change()
{
	read -p "请输入主机名：" host_name
	hostnamectl set-hostname ${host_name}
	echo "ok."
}

network_ping()
{
	ping -c2 www.baidu.com &> /dev/null
	if [ $? -eq 0 ];then
		echo "网络正常"
	else
		echo "网络死了"
	fi
}

network_eth()
{
	mv ${network_path}ifcfg-${network_name} ${network_path}ifcfg-eth0
	sed -i '/^NAME=/c NAME=eth0' ${network_path}ifcfg-eth0
	sed -i '/^DEVICE=/c DEVICE=eth0' ${network_path}ifcfg-eth0
	echo 'GRUB_CMDLINE_LINUX="...... net.ifnames=0"' >> /etc/sysconfig/grub
	grub2-mkconfig -o /boot/grub2/grub.cfg
}

config_yum()
{
	rm -rf ${yum_path}*
	echo "正在获取Base源..."
	curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo &> /dev/null
 	if [ $? -eq 0 ];then
		echo "Base is ok."
	else
		echo "Base Dead!"
		exit
	fi
	yum -y install wget &> /dev/null
	echo "正在获取epel源..."
	wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo &> /dev/null
	if [ $? -eq 0 ];then
		echo "epel ok."
	else
		echo "epel Dead!"
		exit
	fi
}

config_ssh()
{
	sed -i '/^#Port/c Port 2222' ${ssh_path}
	sed -i '/^#PermitRootLogin/c PermitRootLogin NO' ${ssh_path}
	systemctl restart sshd
	if [ $? -eq 0 ];then
		echo "SSH服务配置并重启成功."
	else
		echo "SSH服务启动失败！"
		exit
	fi
}

user_add()
{
	read -p "请出入用户名：" user_name
	useradd ${user_name}
	echo "123" | passwd --stdin ${user_name}
	gpasswd -a ${user_name} wheel
	echo "用户名：${user_name}"
	echo "默认密码：123"
}

root_300s()
{
	sed -i '/HISTSIZE=/a TMOUT=300' /etc/profile
	source /etc/profile
}

time_ntp()
{
	echo "正在安装ntpdate..."
	yum -y install ntpdate &> /dev/null
	if [ $? -eq 0 ];then
		echo "安装成功."
	else
		echo "安装失败！"
		exit
	fi
	ntpdate ntp.sjtu.edu.cn &> /dev/null
	if [ $? -eq 0 ];then
		echo "时间校对成功."
		date
	else
		echo "时间校对失败！"
		exit
	fi
}

while :
do
	list()
	read -p "请输入您的选项：" choose
	case $choose in
	1)
		firewalld_stop
	;;
	2)
		hostname_change
	;;
	3)
		network_ping
	;;
	4)
		network_eth
	;;
	5)
		config_yum
	;;
	6)
		config_ssh
	;;
	7)
		user_add
	;;
	8)
		root_300s
	;;
	9)
		time_ntp
	;;
	esac
done
